name: merged_flutter_project
description: A merged Flutter project from multiple sources.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.4.8
  freezed_annotation: ^2.4.1
  http: ^0.13.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  math_expressions: ^2.5.0
  github: ^9.2.0
  flutter_html: any
  url_strategy: ^0.2.0
  universal_html: ^2.0.4
  mailto: ^2.0.0
  flip_card: ^0.6.0
  url_launcher: ^6.1.2
  carousel_slider: ^4.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.6
  image_gallery_saver: ^2.0.3
  share: ^2.0.4
  path_provider: ^2.0.2
  flutter_dotenv: ^5.0.2
  share_plus: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/work/
    - assets/photos/
    - assets/services/
    - assets/projects/
    - data.json

  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
